version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=caio
      - POSTGRES_PASSWORD=senha123

volumes:
  postgres_data: